#!/bin/bash

# Attempt to minimize benchmark variance by explicitly setting CPU affinity.

set -eu

taskset --cpu-list 1-3 lein with-profiles default,benchmark run -m fastester.core :benchmarks ./resources/select_keys_options.edn

exit 0

